POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidG9ueWUuamltQGdtYWlsLmNvbSIsImlhdCI6MTc2MTc1MjQzOSwiZXhwIjoxNzYxNzU2MDM5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.SxN7vOSHiVfKm2pbj1pxReVvAgr0Xl-DCwGB-ZVyNX4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTc2MTc1MjQzOSwiZXhwIjoxNzYxODM4ODM5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.0fXZh9SNrYv7FY1Fo2uYE8tyoTC6nzIBYH2okRgDgl0"
}
